name: mobilefacenet_flutter_package
description: MobileFaceNet model package for FlutterFlow.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0

flutter:
  assets:
    - assets/models/mobilefacenet.tflite